
error 1: FATAL FAULT `precondition`: debug: is_valid x
Call stack:
fuzion.type.runtime.type.fault.type.install_default.λ.call#1: {base.fum}/fuzion/runtime/fault.fz:38:7:
      fuzion.sys.fatal_fault kind msg
------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fuzion.runtime.fault.cause#1: {base.fum}/eff/fallible.fz:35:6:
  => h e
-----^
fuzion.type.runtime.type.pre_fault.type.install_default.λ.call#1: {base.fum}/fuzion/runtime/pre_fault.fz:39:7:
      fuzion.runtime.fault.cause ("precondition", msg)).default
------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fuzion.runtime.pre_fault.cause#1: {base.fum}/eff/fallible.fz:35:6:
  => h e
-----^
fuzion.runtime.precondition_fault#1: {base.fum}/fuzion/runtime/pre_fault.fz:58:42:
public precondition_fault(msg String) => pre_fault.cause msg
-----------------------------------------^^^^^^^^^^^^^^^^^^^
ex89.pre f: {main.fum}/-:5:7:
      debug: is_valid x
------^^^^^^^^^^^^^^^^^
ex89.precall f: {main.fum}/-:4:5:
    pre
----^^^
      debug: is_valid x
------^^^^^^^^^^^^^^^^^
ex89: {main.fum}/-:14:3:
  f 8
--^^^

*** fatal errors encountered, stopping.
one error.
